version: '3'
services:
  climbing-app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn start:dev"
    ports: 
      - "3000:3000"
    working_dir: /nestjs-climbing-app
    volumes:
      - ./:/nestjs-climbing-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: climbing-app
      JWT_SECRET: \c*VZ)WvnMH.3Ne8[?9d/He+Jccu5:q4;3<;SuD`&t=.-Eq3aA2vA!pML\_KcFT>
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - climbing-app-postgres-data:/var/lib/postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: climbing-app

volumes:
  climbing-app-postgres-data:
